version: '3.7'
services:
  skosmos:
    container_name: skosmos
    image: rossio/skosmos-resolucaold:1.0
#    environment:
 #     FUSEKI_DATASET_1: skosmos
 #   build:
 #     context: ./fuseki/RossioFusekiImage
 #     dockerfile: Dockerfile
    ports:
    - published: 80
      target: 80
    stdin_open: true
    tty: true
    volumes:
    - ./mount:/mount
#    - /root/docker/fuseki/mounts/tdb:/fuseki
    entrypoint: /entrypoint.sh
